### ISSUE TITLE
has issues when hooking unidentified byts

### ISSUE THREAD

**Issue by sodiseng** [TsudaKageyu/minhook#77]
there is my project code
`
PVOID g_adr_func = nullptr;
int Detour_test()
{
	return reinterpret_cast<int (__stdcall*) ()>(g_adr_func)();
}

int main()
{
	MH_STATUS status = MH_UNKNOWN;
	status = MH_Initialize();
	if (MH_OK != status)
	{
		std::cout << "Initlize faild" << std::endl;
		return 0;
	}

	PVOID adr_func = VirtualAlloc(NULL, 0x1000, MEM_COMMIT, PAGE_EXECUTE_READWRITE);
	if (!adr_func)
	{
		std::cout << "allcate faild" << std::endl;
		return 0;
	}
	std::cout << std::hex << adr_func << std::endl;
	uint8_t byts[] = {0xE8, 0xE8, 0x56, 0xFB, 0x60, 0xFE, 0xFF, 0xFF, 0x8B, 0x4D, 0x08, 0x8B, 0xD0};
	memcpy(adr_func, byts, sizeof(byts));
	g_adr_func = adr_func;
	
	
	status = MH_CreateHook(adr_func, Detour_test, NULL);
	if (status != MH_OK)
	{
		std::cout << "CreateHook faild" << std::endl;
		goto out_exit;
	}

	out_exit:
	if (adr_func)
		VirtualFree(adr_func, 0, MEM_RELEASE);

	std::cin.ignore();
}
`

its createhook unsucessfully.
because of the unidentified btys after {0xE8, 0xE8, 0x56, 0xFB, 0x60}
its need to fix,its sure that call{0xe8} is 5 bytes

**Comment by RaMMicHaeL** [comment]
* What error code does `MH_CreateHook` return?
* Upload your compiled exe file, I'll take a look.
* Format your code properly.

**Comment by sodiseng** [comment]
error code: MH_ERROR_UNSUPPORTED_FUNCTION
there is full code:
https://hastebin.com/nowuvusesi.cpp
ty

**Comment by sodiseng** [comment]
> * What error code does `MH_CreateHook` return?
> * Upload your compiled exe file, I'll take a look.
> * Format your code properly.

error code: MH_ERROR_UNSUPPORTED_FUNCTION
there is full code:
https://hastebin.com/nowuvusesi.cpp
ty

**Comment by RaMMicHaeL** [comment]
> there is full code:

Can you upload the compiled exe file? Drop it [here](https://send.firefox.com/) for example.

**Comment by sodiseng** [comment]
> > there is full code:
> 
> Can you upload the compiled exe file? Drop it [here](https://send.firefox.com/) for example.

https://send.firefox.com/download/958add0588221c4c/#oh4rQmHMYVd-qsOr2GS34g

**Comment by RaMMicHaeL** [comment]
It fails here:
https://github.com/TsudaKageyu/minhook/blob/8fda4f5481fed5797dc2651cd91e238e9b3928c6/src/trampoline.c#L125

because the command after the call is invalid:
![image](https://user-images.githubusercontent.com/4129781/55894151-46bbb300-5bc2-11e9-8302-5f11f01cfd9d.png)

it doesn't have to be valid, but due to the way the function is implemented, it's being checked. I'll look at it when I have some spare time and try to fix it. Meanwhile, just make sure that you have a valid next instruction. For the test, you can use e.g. `{0xE8, 0xE8, 0x56, 0xFB, 0x60, 0x90 ... }`. (adding nop = 0x90)

**Comment by sodiseng** [comment]
yes,just a occasional bug.
its cant be hook when the address is hooking,until u path 0x90 first
thanks
