### ISSUE TITLE
Hook fails in certain condition

### ISSUE THREAD

**Issue by NaiJii** [TsudaKageyu/minhook#86]
I'm hooking a virtual function like this : 
`MH_CreateHook(myTarget, &myHook, reinterpret_cast<void**>( &myOriginal ) )`
myTarget is a virtual function I got in a vtable.
If I hook a function in the same vtable that returns the same thing (for exemple myTarget just returns true, and another function in the same vtable also return only true, it will not hook the second one because MinHook thinks it is the same function : 
![image](https://user-images.githubusercontent.com/37872805/76680384-633d4800-65e8-11ea-948d-1231e8393e0b.png)

but works if I remove one of the two functions that returns the same in the same vtable : 
![image](https://user-images.githubusercontent.com/37872805/76680398-77814500-65e8-11ea-9dd2-718baf9f4017.png)

Sorry for my bad english :)

**Comment by m417z** [comment]
It's not that "MinHook thinks it is the same function", it is the same function. You can print the address of all of the functions, and you'll see that not all of the addresses are unique.

What happens is that you have two functions of the form (for example):
```
int func() {
    return 1;
}
```
The compiler detects that they're equivalent, and generates one function which is shared by two or more entries in the vtable.

Depending on what you're trying to do, it might be a better idea to use vtable hooking instead of using MinHook. In any case, MinHook works as expected, and there's nothing to be fixed on MinHook's side.

(note that my answer is a best guess according to the information you provided, which is not complete)

**Comment by NaiJii** [comment]
I see, thanks for the quick answer, didn't know that. 
The thread can be closed
